services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app
      # Mount secret file for password
      - ./backend_management_password.txt:/run/secrets/backend_management_password:ro
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    environment:
      - DATA_SOURCE_URL=http://mockserver:8080/api/data
      - DATA_SOURCE_INTERVAL=1
      - MANAGEMENT_PASSWORD_FILE=/run/secrets/backend_management_password
    depends_on:
      mockserver:
        condition: service_healthy
    networks:
      - dashboard-net

  # http://localhost:4200 - development build of the frontend with hot reloading
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Containerfile
      target: build
    command: npm start -- --host 0.0.0.0 --poll 2000
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dashboard-net

  # http://localhost:8888 - production build of the frontend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "8888:80"
    environment:
      BACKEND_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - dashboard-net

  mockserver:
    container_name: mockserver
    build:
      context: ./mockserver
      dockerfile: Containerfile
    environment:
      DATA_SAMPLE_DIRECTORY: data/2026-03-01/
      DATA_SAMPLE_INTERVAL: 3
    volumes:
      - ./mockserver:/app
    healthcheck:
      test: [ "CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/api/data')" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - dashboard-net

networks:
  dashboard-net:
    driver: bridge
